<a href="https://colab.research.google.com/github/DevaHarshiniModepalli/DevaHarshini425/blob/main/ASSIGNMENT_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [8]:
df=pd.read_csv('/content/drive/MyDrive/Day_7_sales_data.csv')
df

          Date     Product Region    Sales  Profit  Quantity
0   2023-01-02      Tablet   East  1061.81  236.12         7
1   2023-01-06      Laptop  North  1926.07  246.34         8
2   2023-01-03      Tablet   East  1597.99  253.17         3
3   2023-01-20      Tablet  North  1397.99  242.23         1
4   2023-01-04      Laptop   West   734.03  140.36         4
5   2023-01-17      Tablet  North   733.99  188.66         2
6   2023-01-14    Keyboard   East   587.13   82.16         8
7   2023-01-07  Smartphone   East  1799.26  364.97         4
8   2023-01-11  Smartphone   West  1401.67  306.24         2
9   2023-01-01      Laptop  North  1562.11  170.72         6
10  2023-01-19     Monitor  North   530.88  117.59         6
11  2023-01-12      Laptop   West  1954.86  262.16         4
12  2023-01-09     Monitor  North  1748.66  197.62         6
13  2023-01-10  Smartphone  North   818.51  237.19         2
14  2023-01-08      Laptop   East   772.74  226.51         2
15  2023-01-05    Keyboard  North   775.11  202.83         4
16  2023-01-15      Tablet  North   956.36  153.90         8
17  2023-01-18     Monitor   West  1287.13  153.86         7
18  2023-01-13      Tablet   West  1147.92  271.88         9
19  2023-01-16      Tablet  South   936.84  176.15         8

In [9]:
df.head(5)

         Date Product Region    Sales  Profit  Quantity
0  2023-01-02  Tablet   East  1061.81  236.12         7
1  2023-01-06  Laptop  North  1926.07  246.34         8
2  2023-01-03  Tablet   East  1597.99  253.17         3
3  2023-01-20  Tablet  North  1397.99  242.23         1
4  2023-01-04  Laptop   West   734.03  140.36         4

In [10]:
df.describe()

             Sales      Profit   Quantity
count    20.000000   20.000000  20.000000
mean   1186.553000  211.533000   5.050000
std     461.528444   66.916251   2.543826
min     530.880000   82.160000   1.000000
25%     774.517500  166.515000   2.750000
50%    1104.865000  214.670000   5.000000
75%    1571.080000  248.047500   7.250000
max    1954.860000  364.970000   9.000000

In [11]:
df['Sales'].sum()

23731.06

In [12]:
df['Region'].unique()

array(['East', 'North', 'West', 'South'], dtype=object)

In [13]:
# result=
df.groupby('Region')['Sales'].sum()
# print(result)

Region
East      5818.93
North    10449.68
South      936.84
West      6525.61
Name: Sales, dtype: float64

In [14]:
# a=df['Quantity'].describe()
# a[7]

9.0

In [15]:
df.groupby('Product')['Quantity'].sum().idxmax()

'Tablet'

to find the max sold product based on quantity

In [21]:
a=df.groupby('Product')['Profit'].max()
a
#  [df['Profit'] / df['Sales'] * 100]

Product
Keyboard      202.83
Laptop        262.16
Monitor       197.62
Smartphone    364.97
Tablet        271.88
Name: Profit, dtype: float64

In [22]:
# grouped_data = df.groupby('Product')

In [24]:
# sales_per_product = grouped_data['Sales'].sum()
# print(sales_per_product)

Product
Keyboard      1362.24
Laptop        6949.81
Monitor       3566.67
Smartphone    4019.44
Tablet        7832.90
Name: Sales, dtype: float64

In [25]:
# avg_quantity_per_product = grouped_data['Quantity'].mean()
# print(avg_quantity_per_product)

Product
Keyboard      6.000000
Laptop        4.800000
Monitor       6.333333
Smartphone    2.666667
Tablet        5.428571
Name: Quantity, dtype: float64

In [26]:
# max_profit_per_product = grouped_data['Profit'].max()
# print(max_profit_per_product)

Product
Keyboard      202.83
Laptop        262.16
Monitor       197.62
Smartphone    364.97
Tablet        271.88
Name: Profit, dtype: float64

In [27]:
a

Product
Keyboard      202.83
Laptop        262.16
Monitor       197.62
Smartphone    364.97
Tablet        271.88
Name: Profit, dtype: float64